#!/usr/bin/env bash
# script that transfers a file from our client to a server

if [ "$#" -lt 4 ]; then
	echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

# Extract paramters
FILE_PATH=$1
SERVER_IP=$2
USERNAME=$3
SSH_KEY=$4

scp -o StrictHostKeyChecking=no -i "$SSH_KEY" $FILE_PATH" "$USERNAME@$SERVER_IP":~

# Check if scp command was successful
if [ "$?" -eq 0 ]; then
	echo "File transfered successfully"
else
	echo "Failed to transfer file"
fi
