#!/usr/bin/env bash
# Install nginx on web server; nginx should be listening on port 80
# Querying Nginx at its root (/) with a GET request (requesting a page)

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx start
