#!/usr/bin/env bash
# Install nginx on web server; nginx should be listening on port 80
# Querying Nginx at its root (/) with a GET request (requesting a page)

sudo apt -y update
sudo apt install -y nginx
sudio sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/sites-available/default
sudo service nginx restart

nginx_pid=$(pidof nginx)
if [ -n "$nginx_pid" ]; then
	echo "Nginx is running."
else
	echo "Nginx is not running."
fi
