#!/usr/bin/env bash
# Install nginx on web server; nginx should be listening on port 80
# Querying Nginx at its root (/) with a GET request (requesting a page)

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx start
