#!/usr/bin/env bash
# script that cconfigures a new ubuntu machine

sudo apt-get update
sudo apt-get install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo sed -i 'server_name _;/a \\\trewrite ^redirect_me https://github.com/rayoo22 permanent;' /etc/nginx/sites-enabled/default

sudo service nginx restart
