#!/usr/bin/env bash
# script that cconfigures a new ubuntu machine

sudo apt-get update
sudo apt-get install -y nginx
mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
printf %s "server {
	listen 80;
	listen [::]:80 default_server;
	root   /etc/nginx/html;
	index  index.html index.htm;
	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=Eyog3BrJtfA&list=RDEMrwmMfSb9w2PDElXAFaeB3Q&start_radio=1;
	}
}" > /etc/nginx/sites-available/default

sudo service nginx restart
