#!/usr/bin/env bash
# create a script to install and configure HAProxy on lb-01 server
# configure on HAProxy should send traffic to web-01 and web-02 servers

sudo apt-get update
sudo apt-get install -y haproxy

server_config="
frontend ryan-frontend
	bind *:80
	mode http
	default_backend ryan-backend
backend ryan-backend
	balance roundrobin
	server 165186-web-01 35.175.63.113 check
	server 165186-web-02 100.25.34.113 check
"

echo "$server_config" | sudo tee /etc/haproxy/haproxy.cfg >/dev/null

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee /etc/default/haproxy >/dev/null

sudo systemctml restart haproxy.service
