#!/usr/bin/env bash
# what type of network a comp in local is connected to
# type of network could connect an office in one building to another office in a few streets away
# what net do you use when you browse www.google.com from your smartphone (not connected to wifi)
3
2
1
