#!/usr/bin/env bash
# displays "to infinity and beyond" indefinitely
# with sleep 2 in each iteration
# i am invincible whn receiving a SIGTERM sign
trap "echo I am invincible!!!" SIGTERM

while true
do
	echo "To infinity and beyond"
	sleep 2
done
