#!/usr/bin/env bash
# using a while loop to print "Best School"
i=1
while [ $i -le 10 ]
do
	echo "$i"
	case $i in
		4) echo "bad luck from China" ;;
		9) echo "bad luck from Japan" ;;
		17) echo "bad luck from Italy" ;;
	esac
	(( i++ ))
done
